-- WatYouFace — schéma PostgreSQL de référence CIBLE (documentation Phase 8).
-- NE PAS appliquer directement à une base existante : à transformer en migrations Flyway revues/testées.

CREATE TABLE contract (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255), content VARCHAR(5000), version VARCHAR(255),
  active BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(254) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  accepted_contract BOOLEAN NOT NULL DEFAULT FALSE,
  avatar_url VARCHAR(2048), role VARCHAR(16) NOT NULL DEFAULT 'USER',
  contract_id BIGINT REFERENCES contract(id),
  CONSTRAINT ck_users_role CHECK (role IN ('USER','ADMIN'))
);

CREATE TABLE user_contract (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  contract_id BIGINT NOT NULL REFERENCES contract(id),
  accepted BOOLEAN NOT NULL, accepted_at TIMESTAMP,
  CONSTRAINT uq_user_contract UNIQUE (user_id, contract_id)
);

CREATE TABLE video (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255), url VARCHAR(2048), uploaded_at TIMESTAMP,
  uploader_id BIGINT REFERENCES users(id)
);

CREATE TABLE post (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT, image_url VARCHAR(2048), video_url VARCHAR(2048), created_at TIMESTAMP,
  author_id BIGINT REFERENCES users(id)
);

CREATE TABLE comment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL, created_at TIMESTAMP,
  author_id BIGINT NOT NULL REFERENCES users(id),
  post_id BIGINT REFERENCES post(id), video_id BIGINT REFERENCES video(id),
  CONSTRAINT ck_comment_target CHECK ((post_id IS NOT NULL)::integer + (video_id IS NOT NULL)::integer = 1)
);

CREATE TABLE likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id), post_id BIGINT REFERENCES post(id), video_id BIGINT REFERENCES video(id),
  CONSTRAINT ck_like_target CHECK ((post_id IS NOT NULL)::integer + (video_id IS NOT NULL)::integer = 1),
  CONSTRAINT uq_like_user_post UNIQUE (user_id, post_id),
  CONSTRAINT uq_like_user_video UNIQUE (user_id, video_id)
);

CREATE TABLE conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_group BOOLEAN NOT NULL DEFAULT FALSE, title VARCHAR(255), created_at TIMESTAMPTZ
);

CREATE TABLE conversation_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id),
  user_id BIGINT NOT NULL REFERENCES users(id),
  CONSTRAINT uq_conversation_participant UNIQUE (conversation_id, user_id)
);

CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id),
  sender_id BIGINT NOT NULL REFERENCES users(id), receiver_id BIGINT NOT NULL REFERENCES users(id),
  content VARCHAR(2000), sent_at TIMESTAMPTZ, edited BOOLEAN NOT NULL DEFAULT FALSE, deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL, description VARCHAR(2000), price NUMERIC(12,2) NOT NULL,
  image VARCHAR(2048), status VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
  seller_id BIGINT NOT NULL REFERENCES users(id), buyer_id BIGINT REFERENCES users(id),
  CONSTRAINT ck_listing_price CHECK (price > 0),
  CONSTRAINT ck_listing_status CHECK (status IN ('AVAILABLE','PENDING','ACCEPTED','PAID','SHIPPED','RECEIVED','REFUSED'))
);

CREATE TABLE wallet (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  balance NUMERIC(12,2) NOT NULL DEFAULT 0,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
  CONSTRAINT ck_wallet_balance CHECK (balance >= 0)
);

CREATE TABLE transaction (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC(12,2) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'CREATED',
  from_user_id BIGINT NOT NULL REFERENCES users(id), to_user_id BIGINT NOT NULL REFERENCES users(id),
  listing_id BIGINT NOT NULL UNIQUE REFERENCES listings(id), created_at TIMESTAMP NOT NULL,
  CONSTRAINT ck_transaction_amount CHECK (amount > 0),
  CONSTRAINT ck_transaction_status CHECK (status IN ('CREATED','SUCCESS','FAILED','COMPLETED'))
);

CREATE TABLE video_share (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT REFERENCES video(id), sender_id BIGINT REFERENCES users(id),
  receiver_id BIGINT REFERENCES users(id), seen BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_post_created_at ON post (created_at DESC);
CREATE INDEX idx_comment_post_created_at ON comment (post_id, created_at);
CREATE INDEX idx_messages_conversation_sent_at ON messages (conversation_id, sent_at DESC);
CREATE INDEX idx_conversation_users_user ON conversation_users (user_id);
CREATE INDEX idx_listings_status ON listings (status);
CREATE INDEX idx_listings_seller ON listings (seller_id);
CREATE INDEX idx_listings_buyer ON listings (buyer_id);
CREATE INDEX idx_transaction_from_user ON transaction (from_user_id);
CREATE INDEX idx_transaction_to_user ON transaction (to_user_id);
CREATE INDEX idx_video_share_receiver ON video_share (receiver_id);
